receivers:
  otlp:
    protocols:
      http: # OTLP over HTTP: 4318
        endpoint: 0.0.0.0:4318
  zipkin: # Zipkin JSON: 9411
    endpoint: 0.0.0.0:9411

exporters:
  debug: {} # 標準出力に受信データをダンプ

service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
