receivers:
  otlp:
    protocols:
      http: # OTLP over HTTP: 4318
        endpoint: 0.0.0.0:4318

exporters:
  debug: {}
  otlp:
    endpoint: host.docker.internal:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
